### ISSUE TITLE
HttpApiBridge does not handle different media type annotations correctly

### ISSUE THREAD

**Issue by rcchen** [palantir/typescript-service-generator#38]
```
@Produces(MediaType.TEXT_PLAIN)
```
results in
```
mediaType: "application/json"
```

**Comment by ryan10132** [comment]
The actual issue is a bit more involved. 

The "mediaType" variable was poorly named and was actually referring to the media type of the request. I'll be renaming it to "requestMediaType" and adding another field named "responseMediaType"
